<?php

class Init extends Migration {

    public function up()
    {
        DBManager::get()->execute("CREATE TABLE IF NOT EXISTS `converis_projects_by_person_free`
        (
            `id` INT NOT NULL AUTO_INCREMENT,
            `nachname` VARCHAR(255) NULL,
            `vorname` VARCHAR(255) NULL,
            `akademischer_titel` VARCHAR(100) NULL,
            `organisation` VARCHAR(255) NULL,
            `orga_ext_int` VARCHAR(100) NULL,
            `rolle_wissenschaftler` VARCHAR(100) NULL,
            `beginn` TEXT NULL,
            `ende` TEXT NULL,
            `anteil_gesamtförderung_prozent` TEXT NULL,
            `anteil_eigenanteil_prozent` TEXT NULL,
            `nachwuchswissenschaftler` TEXT NULL,
            `projekt_id` INT NULL,
            `projektart` TEXT NULL,
            `projektstatus` VARCHAR(100) NULL,
            `projektnummer` TEXT NULL,
            `kurzbezeichnung` VARCHAR(500) NULL,
            `langbezeichnung` VARCHAR(500) NULL,
            `langbezeichnung_engl` varchar(500) NULL,
            `ueberschrift` VARCHAR(500) NULL,
            `ueberschrift_engl` VARCHAR(500) NULL,
            `kurzbeschreibung` VARCHAR(500) NULL,
            `kurzbeschreibung_engl` VARCHAR(500) NULL,
            `allgemeine_beschreibung` TEXT NULL,
            `allgemeine_beschreibung_engl` TEXT NULL,
            `projekttyp` TEXT NULL,
            `promotionsprogramm` TEXT NULL,
            `projektbeginn` TEXT NULL,
            `projektende` TEXT NULL,
            `verlängerung_bis` TEXT NULL,
            `einstieg_laufendes_projekt` TEXT NULL,
            `ausstieg_laufendes_projekt` TEXT NULL,
            `gesamtkosten` TEXT NULL,
            `gesamtkosten_währung` TEXT NULL,
            `kosten_uni_passau` TEXT NULL,
            `kosten_uni_passau_währung` TEXT NULL,
            `förderquote` TEXT NULL,
            `projektpauschale` TEXT NULL,
            `eigenanteil_forschungspool` TEXT NULL,
            `eigenanteil_fp_währung` TEXT NULL,
            `eigenanteil_mittel_projektleiter` TEXT NULL,
            `eigenanteil_mittel_pl_währung` TEXT NULL,
            `kofinanzierung_mittel_dritter` TEXT NULL,
            `kofin_mittel_dritter_währung` TEXT NULL,
            `summe_netto` TEXT NULL,
            `summe_netto_währung` TEXT NULL,
            `summe_brutto` TEXT NULL,
            `summe_brutto_währung` TEXT NULL,
            `steuersatz_in_prozent` TEXT NULL,
            `umsatzsteuer` TEXT NULL,
            `eigenanteil_uni_passau_gesamt` TEXT NULL,
            `ea_uni_p_gesamt_währung` TEXT NULL,
            `fördersumme` TEXT NULL,
            `fördersumme_währung` TEXT NULL,
            `datum_des_bescheids` TEXT NULL,
            `kommentar_finanzen` TEXT NULL,
            `thematische_klassifizierung` TEXT NULL,
            `personen` TEXT NULL,
            `interne_organisationen` TEXT NULL,
            `externe_organisationen` TEXT NULL,
            `mittelgeber` TEXT NULL,
            `antrag_beginn` TEXT NULL,
            `antrag_ende` TEXT NULL,
            `antrag_abgabedatum` TEXT NULL,
            `antrag_fördersumme` TEXT NULL,
            `antrag_fördersumme_währung` TEXT NULL,
            `antrag_kommentar_finanzen` TEXT NULL,
            `mkdate` INT NOT NULL,
            `chdate` INT NOT NULL,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB ROW_FORMAT=DYNAMIC");

        DBManager::get()->execute("CREATE TABLE IF NOT EXISTS `converis_projects_by_person_third_party`
        (
            `id` INT NOT NULL AUTO_INCREMENT,
            `nachname` VARCHAR(255) NULL,
            `vorname` VARCHAR(255) NULL,
            `akademischer_titel` VARCHAR(100) NULL,
            `organisation` VARCHAR(255) NULL,
            `orga_ext_int` VARCHAR(100) NULL,
            `rolle_wissenschaftler` VARCHAR(100) NULL,
            `beginn` TEXT NULL,
            `ende` TEXT NULL,
            `anteil_gesamtförerung_prozent` TEXT NULL,
            `anteil_eigenanteil_prozent` TEXT NULL,
            `nachwuchswissenschaftler` TEXT NULL,
            `projekt_id` INT NULL,
            `projektart` TEXT NULL,
            `projektstatus` VARCHAR(100) NULL,
            `projektnummer` VARCHAR(100) NULL,
            `kurzbezeichnung` VARCHAR(500) NULL,
            `langbezeichnung` VARCHAR(500) NULL,
            `langbezeichnung_engl` VARCHAR(500) NULL,
            `ueberschrift` VARCHAR(255) NULL,
            `ueberschrift_engl` VARCHAR(255) NULL,
            `kurzbeschreibung` VARCHAR(500) NULL,
            `kurzbeschreibung_engl` VARCHAR(500) NULL,
            `allgemeine_beschreibung` TEXT NULL,
            `allgemeine_beschreibung_engl` TEXT NULL,
            `projekttyp` VARCHAR(100) NULL,
            `promotionsprogramm` TEXT NULL,
            `projektbeginn` TEXT NULL,
            `projektende` TEXT NULL,
            `verlängerung_bis` TEXT NULL,
            `einstieg_laufendes_projekt` TEXT NULL,
            `ausstieg_laufendes_projekt` TEXT NULL,
            `gesamtkosten` TEXT NULL,
            `gesamtkosten_währung` VARCHAR(100) NULL,
            `kosten_uni_passau` TEXT NULL,
            `kosten_uni_passau_währung` VARCHAR(100) NULL,
            `förderquote` VARCHAR(10) NULL,
            `projektpauschale` VARCHAR(255) NULL,
            `eigenanteil_forschungspool` TEXT NULL,
            `eigenanteil_fp_währung` VARCHAR(100) NULL,
            `eigenanteil_mittel_projektleiter` TEXT NULL,
            `eigenanteil_mittel_pl_währung` VARCHAR(100) NULL,
            `kofinanzierung_mittel_dritter` TEXT NULL,
            `kofin_mittel_dritter_währung` VARCHAR(100) NULL,
            `summe_netto` TEXT NULL,
            `summe_netto_währung` VARCHAR(100) NULL,
            `summe_brutto` TEXT NULL,
            `summe_brutto_währung` VARCHAR(100) NULL,
            `steuersatz_in_prozent` TEXT NULL,
            `umsatzsteuer` TEXT NULL,
            `eigenanteil_uni_passau_gesamt` TEXT NULL,
            `ea_uni_p_gesamt_währung` VARCHAR(100) NULL,
            `fördersumme` TEXT NULL,
            `fördersumme_währung` VARCHAR(100) NULL,
            `datum_des_bescheids` TEXT NULL,
            `kommentar_finanzen` TEXT NULL,
            `thematische_klassifizierung` TEXT NULL,
            `personen` TEXT NULL,
            `interne_organisationen` TEXT NULL,
            `externe_organisationen` TEXT NULL,
            `mittelgeber` TEXT NULL,
            `antrag_beginn` TEXT NULL,
            `antrag_ende` TEXT NULL,
            `antrag_abgabedatum` TEXT NULL,
            `antrag_fördersumme` TEXT NULL,
            `antrag_fördersumme_währung` VARCHAR(100) NULL,
            `antrag_kommentar_finanzen` TEXT NULL,
            `mkdate` INT NOT NULL,
            `chdate` INT NOT NULL,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB ROW_FORMAT=DYNAMIC");

        DBManager::get()->execute("CREATE TABLE IF NOT EXISTS `converis_projects_free`
        (
            `id` INT NOT NULL AUTO_INCREMENT,
            `projekt_id` INT NULL,
            `projektart` TEXT NULL,
            `projektstatus` VARCHAR(100) NULL,
            `projektnummer` TEXT NULL,
            `kurzbezeichnung` VARCHAR(500) NULL,
            `langbezeichnung` VARCHAR(500) NULL,
            `langbezeichnung_engl` varchar(500) NULL,
            `ueberschrift` VARCHAR(500) NULL,
            `ueberschrift_engl` VARCHAR(500) NULL,
            `kurzbeschreibung` VARCHAR(500) NULL,
            `kurzbeschreibung_engl` VARCHAR(500) NULL,
            `allgemeine_beschreibung` TEXT NULL,
            `allgemeine_beschreibung_engl` TEXT NULL,
            `projekttyp` TEXT NULL,
            `promotionsprogramm` TEXT NULL,
            `projektbeginn` TEXT NULL,
            `projektende` TEXT NULL,
            `verlängerung_bis` TEXT NULL,
            `einstieg_laufendes_projekt` TEXT NULL,
            `ausstieg_laufendes_projekt` TEXT NULL,
            `gesamtkosten` TEXT NULL,
            `gesamtkosten_währung` TEXT NULL,
            `kosten_uni_passau` TEXT NULL,
            `kosten_uni_passau_währung` TEXT NULL,
            `förderquote` TEXT NULL,
            `projektpauschale` TEXT NULL,
            `eigenanteil_forschungspool` TEXT NULL,
            `eigenanteil_fp_währung` TEXT NULL,
            `eigenanteil_mittel_projektleiter` TEXT NULL,
            `eigenanteil_mittel_pl_währung` TEXT NULL,
            `kofinanzierung_mittel_dritter` TEXT NULL,
            `kofin_mittel_dritter_währung` TEXT NULL,
            `summe_netto` TEXT NULL,
            `summe_netto_währung` TEXT NULL,
            `summe_brutto` TEXT NULL,
            `summe_brutto_währung` TEXT NULL,
            `steuersatz_in_prozent` TEXT NULL,
            `umsatzsteuer` TEXT NULL,
            `eigenanteil_uni_passau_gesamt` TEXT NULL,
            `ea_uni_p_gesamt_währung` TEXT NULL,
            `fördersumme` TEXT NULL,
            `fördersumme_währung` TEXT NULL,
            `datum_des_bescheids` TEXT NULL,
            `kommentar_finanzen` TEXT NULL,
            `thematische_klassifizierung` TEXT NULL,
            `personen` TEXT NULL,
            `interne_organisationen` TEXT NULL,
            `externe_organisationen` TEXT NULL,
            `mittelgeber` TEXT NULL,
            `antrag_beginn` TEXT NULL,
            `antrag_ende` TEXT NULL,
            `antrag_abgabedatum` TEXT NULL,
            `antrag_fördersumme` TEXT NULL,
            `antrag_fördersumme_währung` TEXT NULL,
            `antrag_kommentar_finanzen` TEXT NULL,
            `mkdate` INT NOT NULL,
            `chdate` INT NOT NULL,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB ROW_FORMAT=DYNAMIC");

        DBManager::get()->execute("CREATE TABLE IF NOT EXISTS `converis_projects_third_party`
        (
            `id` INT NOT NULL AUTO_INCREMENT,
            `projekt_id` INT NULL,
            `projektart` TEXT NULL,
            `projektstatus` VARCHAR(100) NULL,
            `projektnummer` VARCHAR(100) NULL,
            `kurzbezeichnung` VARCHAR(500) NULL,
            `langbezeichnung` VARCHAR(500) NULL,
            `langbezeichnung_engl` VARCHAR(500) NULL,
            `ueberschrift` VARCHAR(255) NULL,
            `ueberschrift_engl` VARCHAR(255) NULL,
            `kurzbeschreibung` VARCHAR(500) NULL,
            `kurzbeschreibung_engl` VARCHAR(500) NULL,
            `allgemeine_beschreibung` TEXT NULL,
            `allgemeine_beschreibung_engl` TEXT NULL,
            `projekttyp` VARCHAR(100) NULL,
            `promotionsprogramm` TEXT NULL,
            `projektbeginn` TEXT NULL,
            `projektende` TEXT NULL,
            `verlängerung_bis` TEXT NULL,
            `einstieg_laufendes_projekt` TEXT NULL,
            `ausstieg_laufendes_projekt` TEXT NULL,
            `gesamtkosten` TEXT NULL,
            `gesamtkosten_währung` VARCHAR(100) NULL,
            `kosten_uni_passau` TEXT NULL,
            `kosten_uni_passau_währung` VARCHAR(100) NULL,
            `förderquote` VARCHAR(10) NULL,
            `projektpauschale` VARCHAR(255) NULL,
            `eigenanteil_forschungspool` TEXT NULL,
            `eigenanteil_fp_währung` VARCHAR(100) NULL,
            `eigenanteil_mittel_projektleiter` TEXT NULL,
            `eigenanteil_mittel_pl_währung` VARCHAR(100) NULL,
            `kofinanzierung_mittel_dritter` TEXT NULL,
            `kofin_mittel_dritter_währung` VARCHAR(100) NULL,
            `summe_netto` TEXT NULL,
            `summe_netto_währung` VARCHAR(100) NULL,
            `summe_brutto` TEXT NULL,
            `summe_brutto_währung` VARCHAR(100) NULL,
            `steuersatz_in_prozent` TEXT NULL,
            `umsatzsteuer` TEXT NULL,
            `eigenanteil_uni_passau_gesamt` TEXT NULL,
            `ea_uni_p_gesamt_währung` VARCHAR(100) NULL,
            `fördersumme` TEXT NULL,
            `fördersumme_währung` VARCHAR(100) NULL,
            `datum_des_bescheids` TEXT NULL,
            `kommentar_finanzen` TEXT NULL,
            `thematische_klassifizierung` TEXT NULL,
            `personen` TEXT NULL,
            `interne_organisationen` TEXT NULL,
            `externe_organisationen` TEXT NULL,
            `mittelgeber` TEXT NULL,
            `antrag_beginn` TEXT NULL,
            `antrag_ende` TEXT NULL,
            `antrag_abgabedatum` TEXT NULL,
            `antrag_fördersumme` TEXT NULL,
            `antrag_fördersumme_währung` VARCHAR(100) NULL,
            `antrag_kommentar_finanzen` TEXT NULL,
            `mkdate` INT NOT NULL,
            `chdate` INT NOT NULL,
            PRIMARY KEY (`id`)
        ) ENGINE=InnoDB ROW_FORMAT=DYNAMIC");

        try {
            Config::get()->create('CONVERIS_HOSTNAME', array(
                'value' => 'converis.host.name',
                'type' => 'string',
                'range' => 'global',
                'section' => 'converisplugin',
                'description' => 'Adresse des Converis-Servers'
            ));
            Config::get()->create('CONVERIS_DB_USER', array(
                'value' => 'username',
                'type' => 'string',
                'range' => 'global',
                'section' => 'converisplugin',
                'description' => 'Benutzername für die Datenbankverbindung'
            ));
            Config::get()->create('CONVERIS_DB_PASSWORD', array(
                'value' => 'secret',
                'type' => 'string',
                'range' => 'global',
                'section' => 'converisplugin',
                'description' => 'Passwort für die Datenbankverbindung'
            ));
            Config::get()->create('CONVERIS_DATABASE', array(
                'value' => 'converisdb',
                'type' => 'string',
                'range' => 'global',
                'section' => 'converisplugin',
                'description' => 'Name der Converis-Datenbank'
            ));
        } catch (InvalidArgumentException $e) {}
    }

    public function down()
    {
        DBManager::get()->execute("DROP TABLE IF EXISTS `converis_projects_by_person_free`");
        DBManager::get()->execute("DROP TABLE IF EXISTS `converis_projects_by_person_third_party`");
        DBManager::get()->execute("DROP TABLE IF EXISTS `converis_projects_free`");
        DBManager::get()->execute("DROP TABLE IF EXISTS `converis_projects_third_party`");
    }

}